/*

 */
package vista;

import conexion.DBSentencias;
import controlador.ControladorGeneral;
import controlador.ControladorVista;
import controlador.GestorTabla;
import java.awt.HeadlessException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 
 */
public class ABMUsuario extends javax.swing.JFrame implements DBSentencias {

    
    private ControladorGeneral gg;
    
    private DefaultTableModel modelo;
    private ControladorVista cv;

    public ABMUsuario() {
        try {
            initComponents();
            gg = new ControladorGeneral();
            cv = new ControladorVista();
            modelo = new DefaultTableModel();
            actualizarTabla(consulta5, null);


        } catch (Exception ex) {
            Logger.getLogger(ABMUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btCerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        btModificar = new javax.swing.JButton();
        btEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dniBuscar = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btNuevo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ABM Cliente");
        setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        btCerrar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/power.png"))); // NOI18N
        btCerrar.setText("Cerrar");
        btCerrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btCerrar.setContentAreaFilled(false);
        btCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarActionPerformed(evt);
            }
        });

        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaCliente);

        btModificar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sign-sync_1.png"))); // NOI18N
        btModificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btModificar.setContentAreaFilled(false);
        btModificar.setPreferredSize(new java.awt.Dimension(80, 25));
        btModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarActionPerformed(evt);
            }
        });

        btEliminar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sign-delete_1.png"))); // NOI18N
        btEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btEliminar.setContentAreaFilled(false);
        btEliminar.setMaximumSize(new java.awt.Dimension(83, 23));
        btEliminar.setMinimumSize(new java.awt.Dimension(83, 23));
        btEliminar.setPreferredSize(new java.awt.Dimension(80, 25));
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("DNI:");

        dniBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniBuscarActionPerformed(evt);
            }
        });
        dniBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dniBuscarKeyTyped(evt);
            }
        });

        btBuscar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btBuscar.setContentAreaFilled(false);
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Registros de Usuarios del Sistema");

        btNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencil.png"))); // NOI18N
        btNuevo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btNuevo.setContentAreaFilled(false);
        btNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nuevo");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Editar");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Eliminar");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(btCerrar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(70, 70, 70))
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(169, 169, 169)
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 422, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(31, 31, 31)
                        .add(btNuevo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(33, 33, 33)
                        .add(btModificar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(41, 41, 41)
                        .add(btEliminar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(31, 31, 31)
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(dniBuscar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 143, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(27, 27, 27)
                        .add(btBuscar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jSeparator1)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jScrollPane1)
                        .addContainerGap())))
            .add(jPanel1Layout.createSequentialGroup()
                .add(52, 52, 52)
                .add(jLabel3)
                .add(89, 89, 89)
                .add(jLabel4)
                .add(125, 125, 125)
                .add(jLabel5)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(jLabel2)
                .add(18, 18, 18)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(16, 16, 16)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, btModificar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, btNuevo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel1)
                            .add(dniBuscar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(btBuscar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(btEliminar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3)
                    .add(jLabel4)
                    .add(jLabel5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 23, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 197, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btCerrar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(20, 20, 20))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void actualizarTabla(String consulta, String[] arregloDatoCampo) {
        if (arregloDatoCampo == null) {
            modelo = cv.mostrar(consulta);
        } else {
            modelo = cv.mostrar(consulta, arregloDatoCampo);
        }
        tablaCliente.setModel(modelo);
        tablaCliente.getColumnModel().removeColumn(tablaCliente.getColumnModel().getColumn(0));

    }

    private void btModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tablaCliente.getSelectedRow();//numero fila seleccionada
        int columnaSeleccionada = tablaCliente.getSelectedColumn();//numero de columna seleccionada NO ME INTERESA

        try {
            if (filaSeleccionada == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un cliente de la lista", "Error", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                long valorId = (Long) modelo.getValueAt(filaSeleccionada, 0);


                new AltaUsuario(this, true, valorId).setVisible(true);
            }
        } catch (HeadlessException e) {
            e.printStackTrace();
        }

}//GEN-LAST:event_btModificarActionPerformed

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed
        
        
        String[] salida = {"Si", "No"};
        
        int filaSeleccionada = tablaCliente.getSelectedRow();

        try {
            if (filaSeleccionada == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un cliente de la lista", "Error", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                
                int opcion = JOptionPane.showOptionDialog(null, "el registro se eliminara. \n¿Se encuentra seguro de esta acción?", "Confirmación",
                        javax.swing.JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, salida, salida[0]);
                if (opcion==0) {
                     Long valorId = (Long) modelo.getValueAt(filaSeleccionada, 0);

                //ControladorGeneral gg = new ControladorGeneral();
                String[] arregloDatosCampo = {valorId.toString()};
                gg.ejecutarSentencia(arregloDatosCampo, consulta3);
                actualizarTabla(consulta5, null);
                //gg.cerrarConexion();
                }
                
              
            }
        } catch (HeadlessException e) {
            e.printStackTrace();
        }
}//GEN-LAST:event_btEliminarActionPerformed

    private void btCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarActionPerformed
        // TODO add your handling code here:
        //gg.cerrarConexion();
        System.exit(0);
    }//GEN-LAST:event_btCerrarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
        try {
            if (dniBuscar.getText().equals("")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un DNI", "Error", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                String[] arregloDatoCampo = {dniBuscar.getText()};
                actualizarTabla(consulta4, arregloDatoCampo);
            }
        } catch (HeadlessException e) {
            e.printStackTrace();
        }
}//GEN-LAST:event_btBuscarActionPerformed

    private void dniBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniBuscarActionPerformed

    private void btNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoActionPerformed
    // TODO add your handling code here:
        new AltaUsuario(this, false, new Long(-1)).setVisible(true);
        actualizarTabla(consulta5, null);
        //GestorTabla.vaciaFilasModelo(modelo);
        //ResultSet rs = gg.ejecutarConsulta(null, consulta5);
        //GestorTabla.anhadeFilasDeDatos(rs, modelo);
    }//GEN-LAST:event_btNuevoActionPerformed

    private void dniBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dniBuscarKeyTyped

          try {
            if (dniBuscar.getText().equals("")) {
                String[] arregloDatoCampo = {dniBuscar.getText()};
                actualizarTabla(consulta4, arregloDatoCampo);
            } 
        } catch (HeadlessException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_dniBuscarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ABMUsuario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCerrar;
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btModificar;
    private javax.swing.JButton btNuevo;
    private javax.swing.JTextField dniBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablaCliente;
    // End of variables declaration//GEN-END:variables
}
