/*
 * ABMTabla.java
 *
 * Created on 18 de abril de 2008, 12:13
 */
package vista;

import conexion.DBSentencias;
import controlador.ControladorGeneral;
import controlador.ControladorVista;
import controlador.GestorTabla;
import java.awt.HeadlessException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ing. Gerardo Magni
 */
public class ABMCliente extends javax.swing.JFrame implements DBSentencias {

    /**
     * Creates new form ABMTabla
     */
    private ControladorGeneral gg;
    /**
     * Clase donde se guardan los datos leidos de base de datos
     */
    private DefaultTableModel modelo;
    private ControladorVista cv;

    public ABMCliente() {
        try {
            initComponents();
            gg = new ControladorGeneral();
            cv = new ControladorVista();
            modelo = new DefaultTableModel();
            actualizarTabla(consulta5, null);


        } catch (Exception ex) {
            Logger.getLogger(ABMCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        btNuevo = new javax.swing.JButton();
        btModificar = new javax.swing.JButton();
        btEliminar = new javax.swing.JButton();
        btCerrar = new javax.swing.JButton();
        dniBuscar = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ABM Cliente");
        setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaCliente);

        btNuevo.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btNuevo.setText("Nuevo");
        btNuevo.setMaximumSize(new java.awt.Dimension(83, 23));
        btNuevo.setMinimumSize(new java.awt.Dimension(83, 23));
        btNuevo.setPreferredSize(new java.awt.Dimension(80, 25));
        btNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevoActionPerformed(evt);
            }
        });

        btModificar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btModificar.setText("Modificar");
        btModificar.setPreferredSize(new java.awt.Dimension(80, 25));
        btModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarActionPerformed(evt);
            }
        });

        btEliminar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btEliminar.setText("Eliminar");
        btEliminar.setMaximumSize(new java.awt.Dimension(83, 23));
        btEliminar.setMinimumSize(new java.awt.Dimension(83, 23));
        btEliminar.setPreferredSize(new java.awt.Dimension(80, 25));
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });

        btCerrar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btCerrar.setText("Cerrar");
        btCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarActionPerformed(evt);
            }
        });

        dniBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniBuscarActionPerformed(evt);
            }
        });

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("DNI:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(btNuevo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btModificar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btEliminar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 40, Short.MAX_VALUE)
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(dniBuscar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(btBuscar))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, btCerrar))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btEliminar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btNuevo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btModificar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btBuscar)
                    .add(dniBuscar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .add(42, 42, 42)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 317, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(btCerrar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoActionPerformed
        // TODO add your handling code here:
        new ClienteAdmin(this, false, new Long(-1)).setVisible(true);
        actualizarTabla(consulta5, null);
        //GestorTabla.vaciaFilasModelo(modelo);
        //ResultSet rs = gg.ejecutarConsulta(null, consulta5);
        //GestorTabla.anhadeFilasDeDatos(rs, modelo);


}//GEN-LAST:event_btNuevoActionPerformed

    public void actualizarTabla(String consulta, String[] arregloDatoCampo) {
        if (arregloDatoCampo == null) {
            modelo = cv.mostrar(consulta);
        } else {
            modelo = cv.mostrar(consulta, arregloDatoCampo);
        }
        tablaCliente.setModel(modelo);
        tablaCliente.getColumnModel().removeColumn(tablaCliente.getColumnModel().getColumn(0));

    }

    private void btModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tablaCliente.getSelectedRow();//numero fila seleccionada
        int columnaSeleccionada = tablaCliente.getSelectedColumn();//numero de columna seleccionada NO ME INTERESA

        try {
            if (filaSeleccionada == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un cliente de la lista", "Error", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                Long valorId = (Long) modelo.getValueAt(filaSeleccionada, 0);


                new ClienteAdmin(this, true, valorId).setVisible(true);
            }
        } catch (HeadlessException e) {
            e.printStackTrace();
        }

}//GEN-LAST:event_btModificarActionPerformed

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tablaCliente.getSelectedRow();

        try {
            if (filaSeleccionada == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un cliente de la lista", "Error", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                Long valorId = (Long) modelo.getValueAt(filaSeleccionada, 0);

                //ControladorGeneral gg = new ControladorGeneral();
                String[] arregloDatosCampo = {valorId.toString()};
                gg.ejecutarSentencia(arregloDatosCampo, consulta3);
                actualizarTabla(consulta5, null);
                //gg.cerrarConexion();
            }
        } catch (HeadlessException e) {
            e.printStackTrace();
        }
}//GEN-LAST:event_btEliminarActionPerformed

    private void btCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarActionPerformed
        // TODO add your handling code here:
        //gg.cerrarConexion();
        System.exit(0);
    }//GEN-LAST:event_btCerrarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
        try {
            if (dniBuscar.getText().equals("")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un DNI", "Error", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                String[] arregloDatoCampo = {dniBuscar.getText()};
                actualizarTabla(consulta4, arregloDatoCampo);
            }
        } catch (HeadlessException e) {
            e.printStackTrace();
        }
}//GEN-LAST:event_btBuscarActionPerformed

    private void dniBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ABMCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCerrar;
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btModificar;
    private javax.swing.JButton btNuevo;
    private javax.swing.JTextField dniBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCliente;
    // End of variables declaration//GEN-END:variables
}
